### ISSUE TITLE
Profile Image Update error

### ISSUE THREAD

**Issue by eiko03** [jcergolj/laravellte#40]
First time profile image update error gives.. image is required.. 2nd time it works well

**Comment by jcergolj** [comment]
Hi @eiko03, thanks for the feedback. Sorry, I couldn't reproduce the error. Could you tell me more about it?

**Comment by eiko03** [comment]
not a great ui choice but, I  think #41 this would fix the problem

**Comment by jcergolj** [comment]
Is it possible to deal with this kind of error on the backend? Rather than changing the UI? Thanks.

**Comment by eiko03** [comment]
That Would be a great. But I am in a fix
