### ISSUE TITLE
Alpine.js 3

### ISSUE THREAD

**Issue by madurapa** [jcergolj/laravellte#55]
Any plan upgrade to version 3?

**Comment by jcergolj** [comment]
Sorry, I am swamped, and I don't think I'll have time to invest in this project shortly.  However, I am confident that Alpine 3 won't cause too many issues.

**Comment by madurapa** [comment]
No worries, I will try and let you know. Thanks for this awesome codebase!

**Comment by madurapa** [comment]
Done and updated.
